; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; REQUIRES: riscv-registered-target
; RUN: opt -passes=loop-idiom-vectorize -verify-each -mtriple=riscv64-linux-gnu \
; RUN:   -loop-idiom-vectorize-style=predicated -mattr=+v -S < %s \
; RUN: | FileCheck %s --check-prefix=PREDICATED
; RUN: opt -passes=loop-idiom-vectorize -verify-each -mtriple=riscv64-linux-gnu \
; RUN:   -loop-idiom-vectorize-style=masked -mattr=+v -S < %s \
; RUN: | FileCheck %s --check-prefix=MASKED

; Positive test: accept the scalar `[4 x i8]` GEP form and rewrite it into the
; vectorized load/compare loop.

define i32 @load_compare_to_invariant_gep(ptr %arr, float %max_value, i64 %n) {
; PREDICATED-LABEL: define i32 @load_compare_to_invariant_gep(
; PREDICATED-SAME: ptr [[ARR:%.*]], float [[MAX_VALUE:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; PREDICATED-NEXT:  [[ENTRY:.*]]:
; PREDICATED-NEXT:    [[ENTER_LOOP:%.*]] = icmp ugt i64 [[N]], 1
; PREDICATED-NEXT:    br i1 [[ENTER_LOOP]], label %[[FOR_BODY_PREHEADER:.*]], label %[[CLEANUP:.*]]
; PREDICATED:       [[FOR_BODY_PREHEADER]]:
; PREDICATED-NEXT:    br label %[[MATCH_MIN_IT_CHECK:.*]]
; PREDICATED:       [[MATCH_MIN_IT_CHECK]]:
; PREDICATED-NEXT:    [[TMP0:%.*]] = icmp ule i64 1, [[N]]
; PREDICATED-NEXT:    br i1 [[TMP0]], label %[[MATCH_MEM_CHECK:.*]], label %[[MATCH_LOOP_PRE:.*]], !prof [[PROF0:![0-9]+]]
; PREDICATED:       [[MATCH_MEM_CHECK]]:
; PREDICATED-NEXT:    [[TMP1:%.*]] = getelementptr float, ptr [[ARR]], i64 1
; PREDICATED-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[TMP1]] to i64
; PREDICATED-NEXT:    [[TMP3:%.*]] = getelementptr float, ptr [[ARR]], i64 [[N]]
; PREDICATED-NEXT:    [[TMP4:%.*]] = ptrtoint ptr [[TMP3]] to i64
; PREDICATED-NEXT:    [[TMP5:%.*]] = lshr i64 [[TMP2]], 12
; PREDICATED-NEXT:    [[TMP6:%.*]] = lshr i64 [[TMP4]], 12
; PREDICATED-NEXT:    [[TMP7:%.*]] = icmp ne i64 [[TMP5]], [[TMP6]]
; PREDICATED-NEXT:    br i1 [[TMP7]], label %[[MATCH_LOOP_PRE]], label %[[MATCH_VEC_LOOP_PREHEADER:.*]], !prof [[PROF1:![0-9]+]]
; PREDICATED:       [[MATCH_VEC_LOOP_PREHEADER]]:
; PREDICATED-NEXT:    br label %[[MATCH_VEC_LOOP:.*]]
; PREDICATED:       [[MATCH_VEC_LOOP]]:
; PREDICATED-NEXT:    [[MATCH_VECTOR_INDEX:%.*]] = phi i64 [ 1, %[[MATCH_VEC_LOOP_PREHEADER]] ], [ [[TMP13:%.*]], %[[MATCH_VEC_LOOP_INC:.*]] ]
; PREDICATED-NEXT:    [[AVL:%.*]] = sub nuw nsw i64 [[N]], [[MATCH_VECTOR_INDEX]]
; PREDICATED-NEXT:    [[TMP8:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 4, i1 true)
; PREDICATED-NEXT:    [[TMP9:%.*]] = getelementptr inbounds float, ptr [[ARR]], i64 [[MATCH_VECTOR_INDEX]]
; PREDICATED-NEXT:    [[MATCH_LOAD:%.*]] = call <vscale x 4 x float> @llvm.vp.load.nxv4f32.p0(ptr [[TMP9]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP8]])
; PREDICATED-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 4 x float> poison, float [[MAX_VALUE]], i64 0
; PREDICATED-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 4 x float> [[DOTSPLATINSERT]], <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer
; PREDICATED-NEXT:    [[MATCH_CMP:%.*]] = call <vscale x 4 x i1> @llvm.vp.fcmp.nxv4f32(<vscale x 4 x float> [[MATCH_LOAD]], <vscale x 4 x float> [[DOTSPLAT]], metadata !"oeq", <vscale x 4 x i1> splat (i1 true), i32 [[TMP8]])
; PREDICATED-NEXT:    [[TMP10:%.*]] = call i32 @llvm.vp.cttz.elts.i32.nxv4i1(<vscale x 4 x i1> [[MATCH_CMP]], i1 false, <vscale x 4 x i1> splat (i1 true), i32 [[TMP8]])
; PREDICATED-NEXT:    [[TMP11:%.*]] = icmp ne i32 [[TMP10]], [[TMP8]]
; PREDICATED-NEXT:    br i1 [[TMP11]], label %[[MATCH_VEC_LOOP_FOUND:.*]], label %[[MATCH_VEC_LOOP_INC]]
; PREDICATED:       [[MATCH_VEC_LOOP_INC]]:
; PREDICATED-NEXT:    [[TMP12:%.*]] = zext i32 [[TMP8]] to i64
; PREDICATED-NEXT:    [[TMP13]] = add nuw nsw i64 [[MATCH_VECTOR_INDEX]], [[TMP12]]
; PREDICATED-NEXT:    [[TMP14:%.*]] = icmp ne i64 [[TMP13]], [[N]]
; PREDICATED-NEXT:    br i1 [[TMP14]], label %[[MATCH_VEC_LOOP]], label %[[MATCH_END:.*]]
; PREDICATED:       [[MATCH_VEC_LOOP_FOUND]]:
; PREDICATED-NEXT:    [[CTZ:%.*]] = phi i32 [ [[TMP10]], %[[MATCH_VEC_LOOP]] ]
; PREDICATED-NEXT:    [[MATCH_VECTOR_INDEX2:%.*]] = phi i64 [ [[MATCH_VECTOR_INDEX]], %[[MATCH_VEC_LOOP]] ]
; PREDICATED-NEXT:    [[TMP15:%.*]] = zext i32 [[CTZ]] to i64
; PREDICATED-NEXT:    [[TMP16:%.*]] = add nuw nsw i64 [[MATCH_VECTOR_INDEX2]], [[TMP15]]
; PREDICATED-NEXT:    br label %[[MATCH_END]]
; PREDICATED:       [[MATCH_LOOP_PRE]]:
; PREDICATED-NEXT:    br label %[[MATCH_LOOP:.*]]
; PREDICATED:       [[MATCH_LOOP]]:
; PREDICATED-NEXT:    [[MATCH_INDEX:%.*]] = phi i64 [ 1, %[[MATCH_LOOP_PRE]] ], [ [[TMP20:%.*]], %[[MATCH_LOOP_INC:.*]] ]
; PREDICATED-NEXT:    [[TMP17:%.*]] = getelementptr inbounds float, ptr [[ARR]], i64 [[MATCH_INDEX]]
; PREDICATED-NEXT:    [[TMP18:%.*]] = load float, ptr [[TMP17]], align 4
; PREDICATED-NEXT:    [[TMP19:%.*]] = fcmp oeq float [[TMP18]], [[MAX_VALUE]]
; PREDICATED-NEXT:    br i1 [[TMP19]], label %[[MATCH_END]], label %[[MATCH_LOOP_INC]]
; PREDICATED:       [[MATCH_LOOP_INC]]:
; PREDICATED-NEXT:    [[TMP20]] = add nuw nsw i64 [[MATCH_INDEX]], 1
; PREDICATED-NEXT:    [[TMP21:%.*]] = icmp eq i64 [[TMP20]], [[N]]
; PREDICATED-NEXT:    br i1 [[TMP21]], label %[[MATCH_END]], label %[[MATCH_LOOP]]
; PREDICATED:       [[MATCH_END]]:
; PREDICATED-NEXT:    [[MATCH_RESULT:%.*]] = phi i64 [ [[N]], %[[MATCH_LOOP_INC]] ], [ [[MATCH_INDEX]], %[[MATCH_LOOP]] ], [ [[N]], %[[MATCH_VEC_LOOP_INC]] ], [ [[TMP16]], %[[MATCH_VEC_LOOP_FOUND]] ]
; PREDICATED-NEXT:    br i1 true, label %[[LOAD_COMPARE:.*]], label %[[FOR_BODY:.*]]
; PREDICATED:       [[FOR_BODY]]:
; PREDICATED-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_INC:.*]] ], [ 1, %[[MATCH_END]] ]
; PREDICATED-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[ARR]], i64 [[INDVARS_IV]]
; PREDICATED-NEXT:    [[TMP22:%.*]] = load float, ptr [[ARRAYIDX]], align 4
; PREDICATED-NEXT:    [[CMP1:%.*]] = fcmp oeq float [[TMP22]], [[MAX_VALUE]]
; PREDICATED-NEXT:    br i1 [[CMP1]], label %[[CLEANUP_SPLIT_LOOP_EXIT:.*]], label %[[FOR_INC]]
; PREDICATED:       [[FOR_INC]]:
; PREDICATED-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; PREDICATED-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[N]]
; PREDICATED-NEXT:    br i1 [[EXITCOND_NOT]], label %[[CLEANUP_LOOPEXIT:.*]], label %[[FOR_BODY]]
; PREDICATED:       [[CLEANUP_SPLIT_LOOP_EXIT]]:
; PREDICATED-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[MATCH_RESULT]], %[[FOR_BODY]] ], [ [[MATCH_RESULT]], %[[LOAD_COMPARE]] ]
; PREDICATED-NEXT:    [[TMP23:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; PREDICATED-NEXT:    br label %[[CLEANUP]]
; PREDICATED:       [[LOAD_COMPARE]]:
; PREDICATED-NEXT:    [[TMP24:%.*]] = icmp eq i64 [[MATCH_RESULT]], [[N]]
; PREDICATED-NEXT:    br i1 [[TMP24]], label %[[CLEANUP_LOOPEXIT]], label %[[CLEANUP_SPLIT_LOOP_EXIT]]
; PREDICATED:       [[CLEANUP_LOOPEXIT]]:
; PREDICATED-NEXT:    br label %[[CLEANUP]]
; PREDICATED:       [[CLEANUP]]:
; PREDICATED-NEXT:    [[MAX_IDX_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[TMP23]], %[[CLEANUP_SPLIT_LOOP_EXIT]] ], [ 0, %[[CLEANUP_LOOPEXIT]] ]
; PREDICATED-NEXT:    ret i32 [[MAX_IDX_0]]
;
; MASKED-LABEL: define i32 @load_compare_to_invariant_gep(
; MASKED-SAME: ptr [[ARR:%.*]], float [[MAX_VALUE:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; MASKED-NEXT:  [[ENTRY:.*]]:
; MASKED-NEXT:    [[ENTER_LOOP:%.*]] = icmp ugt i64 [[N]], 1
; MASKED-NEXT:    br i1 [[ENTER_LOOP]], label %[[FOR_BODY_PREHEADER:.*]], label %[[CLEANUP:.*]]
; MASKED:       [[FOR_BODY_PREHEADER]]:
; MASKED-NEXT:    br label %[[MATCH_MIN_IT_CHECK:.*]]
; MASKED:       [[MATCH_MIN_IT_CHECK]]:
; MASKED-NEXT:    [[TMP0:%.*]] = icmp ule i64 1, [[N]]
; MASKED-NEXT:    br i1 [[TMP0]], label %[[MATCH_MEM_CHECK:.*]], label %[[MATCH_LOOP_PRE:.*]], !prof [[PROF0:![0-9]+]]
; MASKED:       [[MATCH_MEM_CHECK]]:
; MASKED-NEXT:    [[TMP1:%.*]] = getelementptr float, ptr [[ARR]], i64 1
; MASKED-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[TMP1]] to i64
; MASKED-NEXT:    [[TMP3:%.*]] = getelementptr float, ptr [[ARR]], i64 [[N]]
; MASKED-NEXT:    [[TMP4:%.*]] = ptrtoint ptr [[TMP3]] to i64
; MASKED-NEXT:    [[TMP5:%.*]] = lshr i64 [[TMP2]], 12
; MASKED-NEXT:    [[TMP6:%.*]] = lshr i64 [[TMP4]], 12
; MASKED-NEXT:    [[TMP7:%.*]] = icmp ne i64 [[TMP5]], [[TMP6]]
; MASKED-NEXT:    br i1 [[TMP7]], label %[[MATCH_LOOP_PRE]], label %[[MATCH_VEC_LOOP_PREHEADER:.*]], !prof [[PROF1:![0-9]+]]
; MASKED:       [[MATCH_VEC_LOOP_PREHEADER]]:
; MASKED-NEXT:    [[TMP8:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 1, i64 [[N]])
; MASKED-NEXT:    [[TMP9:%.*]] = call i64 @llvm.vscale.i64()
; MASKED-NEXT:    [[TMP10:%.*]] = mul nuw nsw i64 [[TMP9]], 4
; MASKED-NEXT:    br label %[[MATCH_VEC_LOOP:.*]]
; MASKED:       [[MATCH_VEC_LOOP]]:
; MASKED-NEXT:    [[MATCH_VEC_LOOP_PRED:%.*]] = phi <vscale x 4 x i1> [ [[TMP8]], %[[MATCH_VEC_LOOP_PREHEADER]] ], [ [[TMP17:%.*]], %[[MATCH_VEC_LOOP_INC:.*]] ]
; MASKED-NEXT:    [[MATCH_VEC_INDEX:%.*]] = phi i64 [ 1, %[[MATCH_VEC_LOOP_PREHEADER]] ], [ [[TMP16:%.*]], %[[MATCH_VEC_LOOP_INC]] ]
; MASKED-NEXT:    [[TMP11:%.*]] = getelementptr inbounds float, ptr [[ARR]], i64 [[MATCH_VEC_INDEX]]
; MASKED-NEXT:    [[TMP12:%.*]] = call <vscale x 4 x float> @llvm.masked.load.nxv4f32.p0(ptr align 4 [[TMP11]], <vscale x 4 x i1> [[MATCH_VEC_LOOP_PRED]], <vscale x 4 x float> zeroinitializer)
; MASKED-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 4 x float> poison, float [[MAX_VALUE]], i64 0
; MASKED-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 4 x float> [[DOTSPLATINSERT]], <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer
; MASKED-NEXT:    [[TMP13:%.*]] = fcmp oeq <vscale x 4 x float> [[TMP12]], [[DOTSPLAT]]
; MASKED-NEXT:    [[TMP14:%.*]] = select <vscale x 4 x i1> [[MATCH_VEC_LOOP_PRED]], <vscale x 4 x i1> [[TMP13]], <vscale x 4 x i1> zeroinitializer
; MASKED-NEXT:    [[TMP15:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP14]])
; MASKED-NEXT:    br i1 [[TMP15]], label %[[MATCH_VEC_LOOP_FOUND:.*]], label %[[MATCH_VEC_LOOP_INC]]
; MASKED:       [[MATCH_VEC_LOOP_INC]]:
; MASKED-NEXT:    [[TMP16]] = add nuw nsw i64 [[MATCH_VEC_INDEX]], [[TMP10]]
; MASKED-NEXT:    [[TMP17]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP16]], i64 [[N]])
; MASKED-NEXT:    [[TMP18:%.*]] = extractelement <vscale x 4 x i1> [[TMP17]], i64 0
; MASKED-NEXT:    br i1 [[TMP18]], label %[[MATCH_VEC_LOOP]], label %[[MATCH_END:.*]]
; MASKED:       [[MATCH_VEC_LOOP_FOUND]]:
; MASKED-NEXT:    [[MATCH_VEC_FOUND_PRED:%.*]] = phi <vscale x 4 x i1> [ [[TMP14]], %[[MATCH_VEC_LOOP]] ]
; MASKED-NEXT:    [[MATCH_VEC_LAST_LOOP_PRED:%.*]] = phi <vscale x 4 x i1> [ [[MATCH_VEC_LOOP_PRED]], %[[MATCH_VEC_LOOP]] ]
; MASKED-NEXT:    [[MATCH_VEC_FOUND_INDEX:%.*]] = phi i64 [ [[MATCH_VEC_INDEX]], %[[MATCH_VEC_LOOP]] ]
; MASKED-NEXT:    [[TMP19:%.*]] = and <vscale x 4 x i1> [[MATCH_VEC_LAST_LOOP_PRED]], [[MATCH_VEC_FOUND_PRED]]
; MASKED-NEXT:    [[TMP20:%.*]] = call i32 @llvm.experimental.cttz.elts.i32.nxv4i1(<vscale x 4 x i1> [[TMP19]], i1 true)
; MASKED-NEXT:    [[TMP21:%.*]] = zext i32 [[TMP20]] to i64
; MASKED-NEXT:    [[TMP22:%.*]] = add nuw nsw i64 [[MATCH_VEC_FOUND_INDEX]], [[TMP21]]
; MASKED-NEXT:    br label %[[MATCH_END]]
; MASKED:       [[MATCH_LOOP_PRE]]:
; MASKED-NEXT:    br label %[[MATCH_LOOP:.*]]
; MASKED:       [[MATCH_LOOP]]:
; MASKED-NEXT:    [[MATCH_INDEX:%.*]] = phi i64 [ 1, %[[MATCH_LOOP_PRE]] ], [ [[TMP26:%.*]], %[[MATCH_LOOP_INC:.*]] ]
; MASKED-NEXT:    [[TMP23:%.*]] = getelementptr inbounds float, ptr [[ARR]], i64 [[MATCH_INDEX]]
; MASKED-NEXT:    [[TMP24:%.*]] = load float, ptr [[TMP23]], align 4
; MASKED-NEXT:    [[TMP25:%.*]] = fcmp oeq float [[TMP24]], [[MAX_VALUE]]
; MASKED-NEXT:    br i1 [[TMP25]], label %[[MATCH_END]], label %[[MATCH_LOOP_INC]]
; MASKED:       [[MATCH_LOOP_INC]]:
; MASKED-NEXT:    [[TMP26]] = add nuw nsw i64 [[MATCH_INDEX]], 1
; MASKED-NEXT:    [[TMP27:%.*]] = icmp eq i64 [[TMP26]], [[N]]
; MASKED-NEXT:    br i1 [[TMP27]], label %[[MATCH_END]], label %[[MATCH_LOOP]]
; MASKED:       [[MATCH_END]]:
; MASKED-NEXT:    [[MATCH_RESULT:%.*]] = phi i64 [ [[N]], %[[MATCH_LOOP_INC]] ], [ [[MATCH_INDEX]], %[[MATCH_LOOP]] ], [ [[N]], %[[MATCH_VEC_LOOP_INC]] ], [ [[TMP22]], %[[MATCH_VEC_LOOP_FOUND]] ]
; MASKED-NEXT:    br i1 true, label %[[LOAD_COMPARE:.*]], label %[[FOR_BODY:.*]]
; MASKED:       [[FOR_BODY]]:
; MASKED-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_INC:.*]] ], [ 1, %[[MATCH_END]] ]
; MASKED-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[ARR]], i64 [[INDVARS_IV]]
; MASKED-NEXT:    [[TMP28:%.*]] = load float, ptr [[ARRAYIDX]], align 4
; MASKED-NEXT:    [[CMP1:%.*]] = fcmp oeq float [[TMP28]], [[MAX_VALUE]]
; MASKED-NEXT:    br i1 [[CMP1]], label %[[CLEANUP_SPLIT_LOOP_EXIT:.*]], label %[[FOR_INC]]
; MASKED:       [[FOR_INC]]:
; MASKED-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; MASKED-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[N]]
; MASKED-NEXT:    br i1 [[EXITCOND_NOT]], label %[[CLEANUP_LOOPEXIT:.*]], label %[[FOR_BODY]]
; MASKED:       [[CLEANUP_SPLIT_LOOP_EXIT]]:
; MASKED-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[MATCH_RESULT]], %[[FOR_BODY]] ], [ [[MATCH_RESULT]], %[[LOAD_COMPARE]] ]
; MASKED-NEXT:    [[TMP29:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; MASKED-NEXT:    br label %[[CLEANUP]]
; MASKED:       [[LOAD_COMPARE]]:
; MASKED-NEXT:    [[TMP30:%.*]] = icmp eq i64 [[MATCH_RESULT]], [[N]]
; MASKED-NEXT:    br i1 [[TMP30]], label %[[CLEANUP_LOOPEXIT]], label %[[CLEANUP_SPLIT_LOOP_EXIT]]
; MASKED:       [[CLEANUP_LOOPEXIT]]:
; MASKED-NEXT:    br label %[[CLEANUP]]
; MASKED:       [[CLEANUP]]:
; MASKED-NEXT:    [[MAX_IDX_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[TMP29]], %[[CLEANUP_SPLIT_LOOP_EXIT]] ], [ 0, %[[CLEANUP_LOOPEXIT]] ]
; MASKED-NEXT:    ret i32 [[MAX_IDX_0]]
;
entry:
  %enter.loop = icmp ugt i64 %n, 1
  br i1 %enter.loop, label %for.body, label %cleanup

for.body:
  %indvars.iv = phi i64 [ 1, %entry ], [ %indvars.iv.next, %for.inc ]
  %arrayidx = getelementptr inbounds nuw [4 x i8], ptr %arr, i64 %indvars.iv
  %0 = load float, ptr %arrayidx, align 4
  %cmp1 = fcmp oeq float %0, %max_value
  br i1 %cmp1, label %cleanup.split.loop.exit, label %for.inc

for.inc:
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, %n
  br i1 %exitcond.not, label %cleanup.loopexit, label %for.body

cleanup.split.loop.exit:
  %1 = trunc i64 %indvars.iv to i32
  br label %cleanup

cleanup.loopexit:
  br label %cleanup

cleanup:
  %max_idx.0 = phi i32 [ 0, %entry ], [ %1, %cleanup.split.loop.exit ], [ 0, %cleanup.loopexit ]
  ret i32 %max_idx.0
}
