; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; REQUIRES: riscv-registered-target
; RUN: opt -passes=loop-idiom-vectorize -verify-each -mtriple=riscv64-linux-gnu \
; RUN:   -loop-idiom-vectorize-style=predicated -mattr=+v -S < %s \
; RUN: | FileCheck %s --check-prefix=CHECK
; RUN: opt -passes=loop-idiom-vectorize -verify-each -mtriple=riscv64-linux-gnu \
; RUN:   -loop-idiom-vectorize-style=masked -mattr=+v -S < %s \
; RUN: | FileCheck %s --check-prefix=CHECK

; Do not vectorize when the latch increment escapes the loop. The transform
; only reconstructs the found index, so vectorizing this shape would produce
; invalid IR.

define i64 @load_compare_to_invariant_indexinc_liveout(ptr %arr, float %key, i64 %n) {
; CHECK-LABEL: define i64 @load_compare_to_invariant_indexinc_liveout(
; CHECK-SAME: ptr [[ARR:%.*]], float [[KEY:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 1, %[[ENTRY]] ], [ [[NEXT:%.*]], %[[FOR_INC:.*]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[ARR]], i64 [[I]]
; CHECK-NEXT:    [[LD:%.*]] = load float, ptr [[GEP]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp oeq float [[LD]], [[KEY]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[EXIT_FOUND:.*]], label %[[FOR_INC]]
; CHECK:       [[FOR_INC]]:
; CHECK-NEXT:    [[NEXT]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[EXIT_LOOPEXIT:.*]], label %[[FOR_BODY]]
; CHECK:       [[EXIT_FOUND]]:
; CHECK-NEXT:    [[I_LCSSA:%.*]] = phi i64 [ [[I]], %[[FOR_BODY]] ]
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    [[NEXT_LCSSA:%.*]] = phi i64 [ [[NEXT]], %[[FOR_INC]] ]
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES:%.*]] = phi i64 [ [[I_LCSSA]], %[[EXIT_FOUND]] ], [ [[NEXT_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i64 [[RES]]
;
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 1, %entry ], [ %next, %for.inc ]
  %gep = getelementptr inbounds nuw [4 x i8], ptr %arr, i64 %i
  %ld = load float, ptr %gep, align 4
  %cmp = fcmp oeq float %ld, %key
  br i1 %cmp, label %exit.found, label %for.inc

for.inc:
  %next = add nuw nsw i64 %i, 1
  %exitcond = icmp eq i64 %next, %n
  br i1 %exitcond, label %exit, label %for.body

exit.found:
  br label %exit

exit:
  %res = phi i64 [ %i, %exit.found ], [ %next, %for.inc ]
  ret i64 %res
}
